-- 물고기 종류 별 대어 찾기
SELECT SUB.ID, FNI.FISH_NAME, SUB.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH,
           RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RK
    FROM FISH_INFO
) AS SUB
JOIN FISH_NAME_INFO FNI ON SUB.FISH_TYPE = FNI.FISH_TYPE
WHERE RK = 1
ORDER BY 1 ASC