-- 각 CAR_ID 별로 새로운 컬럼 만들어서 해당 날짜 안에 대여중인 기록 있으면 대여중으로 표시
SELECT CAR_ID, 
    CASE
        WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) = 1 THEN '대여중' ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC